# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.1'

services:

  dotnetbank:
    build: .
    ports:
      - 5000:80
    environment:
      String: 'mongodb://172.17.0.1:27017'

  monogodb:
    build: .
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
